### ISSUE TITLE
Version on the NPM site

### ISSUE THREAD

**Issue by Nordes** [iaincollins/tabletojson#24]
Hi, would it be possible to update the version of the package on the NPM repository?

**Comment by iaincollins** [comment]
Thanks for the poke.

Ugh, yeah I have been putting this off because I haven't found the time to write tests yet and previous updates have broken old behaviour as a result.

I'm going to just bump the version number to 0.7.0 now and write some tests after the fact because otherwise I never will.

I figure people can just revert to 0.6.0 if it does something they don't want now and that's better than never updating it.

**Comment by iaincollins** [comment]
Resolved. Have also updated the examples and the README.

**Comment by Nordes** [comment]
Thank you a lot :)

**Comment by iaincollins** [comment]
Your welcome! Thanks for the reminder :)
